version: '3'

services:

  db:
    container_name: carrentaldb
    image: postgres
    hostname: db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASWORD: password
    ports:
      - 5432:5432
    networks:
      - carrentalnet

  carrentalapi:
    container_name: carrentalapi
    image: mjsong/carrentalapi:v1
    hostname: carrentalapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - carrentalnet
    volumes:
      - .:/go/src/CarRental
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  carrentalnet:
    driver: bridge
